apiVersion: autoscaling/v2beta2
kind: VerticalPodAutoscaler
metadata:
  name: dan-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       dan-deployment
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        cpu: 50m
        memory: 50Mi
      maxAllowed:
        cpu: 1
        memory: 1Gi
