apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
  namespace: prod
spec:
  selector:
    matchLabels:
      app: hello-node
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: hello-node
          image: k8s.gcr.io/echoserver:1.4
          ports:
            - containerPort: 8080
