apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "16Mi"
        cpu: "50m"       # 500milliCPUs (1/2 CPU)
      limits:
        memory: "128Mi"
        cpu: "100m"
    volumeMounts:
    - name: my-volume
      mountPath: /data
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: pvc-1
